In [93]:
import numpy as np
import cupy as cp
import cupyx

for dtype in np.complex64, np.complex128:
    for sparse_cls in (
        cupyx.scipy.sparse.csr_matrix, cupyx.scipy.sparse.csc_matrix, cupyx.scipy.sparse.coo_matrix
    ):
        
        a = cp.array([
            (1, 1j),
            (1j, -1-1j)

        ]).astype(dtype)
        sp = sparse_cls(a)
        check = sp.todense()
        if not np.allclose(a, check):
            print(dtype, sparse_cls, "*** RESULTS DIFFER ***")
            print("nonzeros", a[a != 0])
            print("data", sp.data)
            print("sums", a.sum(), sp.sum())
            print("a\n", a)
            print("check\n", check)
            print("diff\n", check - a)
        else:
            print(dtype, sparse_cls, "ok")

<class 'numpy.complex64'> <class 'cupyx.scipy.sparse._csr.csr_matrix'> ok
<class 'numpy.complex64'> <class 'cupyx.scipy.sparse._csc.csc_matrix'> ok
<class 'numpy.complex64'> <class 'cupyx.scipy.sparse._coo.coo_matrix'> ok
<class 'numpy.complex128'> <class 'cupyx.scipy.sparse._csr.csr_matrix'> *** RESULTS DIFFER ***
nonzeros [ 1.+0.j  0.+1.j  0.+1.j -1.-1.j]
data [ 1.+0.j -1.-1.j]
sums 1j -1j
a
 [[ 1.+0.j  0.+1.j]
 [ 0.+1.j -1.-1.j]]
check
 [[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.-1.j]]
diff
 [[0.+0.j 0.-1.j]
 [0.-1.j 0.+0.j]]
<class 'numpy.complex128'> <class 'cupyx.scipy.sparse._csc.csc_matrix'> *** RESULTS DIFFER ***
nonzeros [ 1.+0.j  0.+1.j  0.+1.j -1.-1.j]
data [ 1.+0.j -1.-1.j]
sums 1j -1j
a
 [[ 1.+0.j  0.+1.j]
 [ 0.+1.j -1.-1.j]]
check
 [[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.-1.j]]
diff
 [[0.+0.j 0.-1.j]
 [0.-1.j 0.+0.j]]
<class 'numpy.complex128'> <class 'cupyx.scipy.sparse._coo.coo_matrix'> ok


In [72]:
a = np.array([
    (1, 1j),
    (1j, -1-1j)
    
]).astype(np.complex128)

In [73]:
a

(array([[ 1.+0.j,  0.+1.j],
        [ 0.+1.j, -1.-1.j]]),
 array([[ 1.+0.j,  0.+1.j],
        [ 0.+1.j, -1.-1.j]]))

In [79]:
aa = cp.array(a)
aa

array([[ 1.+0.j,  0.+1.j],
       [ 0.+1.j, -1.-1.j]])

In [78]:
left = cupyx.scipy.sparse.csr_matrix(aa)
left

In [88]:
check = left.todense()
print("allclose", np.allclose(aa, check))
print("aa\n", aa)
print("check\n", check)
print("diff\n", check - aa)

allclose False
aa
 [[ 1.+0.j  0.+1.j]
 [ 0.+1.j -1.-1.j]]
check
 [[ 1.+0.j  0.+0.j]
 [ 0.+0.j -1.-1.j]]
diff
 [[0.+0.j 0.-1.j]
 [0.-1.j 0.+0.j]]


In [81]:
check - aa

array([[0.+0.j, 0.-1.j],
       [0.-1.j, 0.+0.j]])