In [8]:
import numpy as np

from libertem import api
from libertem.udf.stddev import StdDevUDF
from libertem.udf.sum import SumUDF

In [2]:
ctx = api.Context()

In [3]:
ds = ctx.load("auto", path='/cachedata/users/clausen/libertem-test-data/Capture52/Capture52_.gtg')

In [5]:
roi = np.ones(ds.shape.nav, dtype=bool)

In [4]:
stddev_1 = ctx.run_udf(udf=StdDevUDF(), dataset=ds)

In [6]:
stddev_2 = ctx.run_udf(udf=StdDevUDF(), dataset=ds, roi=roi)

In [7]:
stddev_1['varsum'].data - stddev_2['varsum'].data

array([[-2898.28677107, -3094.03116246, -2845.51818182, ...,
           73.33842628,    73.33842628,   165.01145913],
       [-5599.76232175, -5465.11568946, -5457.41959511, ...,
          293.35370512,   293.35370512,   293.35370512],
       [-5526.12851732, -6714.48932709, -5489.48139165, ...,
          293.35370512,   293.35370512,   293.35370512],
       ...,
       [-6564.77091291, -8518.55307487, -6456.46292335, ...,
          293.35370512,   293.35370512,   293.35370512],
       [-6176.62653107, -6114.268637  , -5895.25560224, ...,
          293.35370512,   293.35370512,   293.35370512],
       [-5354.94717341, -6522.53803476, -5615.84924242, ...,
          293.35370512,   293.35370512,   165.01145913]])

In [14]:
stddev_1['sum'].data - stddev_2['sum'].data

array([[ -6276.,  -6082.,  -6137., ...,  -7200.,  -7200., -10800.],
       [-14272., -13145., -12965., ..., -14400., -14400., -14400.],
       [-13600., -13139., -12976., ..., -14400., -14400., -14400.],
       ...,
       [-14121., -12043., -13768., ..., -14400., -14400., -14400.],
       [-13456., -13456., -13915., ..., -14400., -14400., -14400.],
       [-12909., -12558., -13804., ..., -14400., -14400., -10800.]])

In [15]:
stddev_1['num_frames'].data - stddev_2['num_frames'].data

array([0])

In [9]:
sum_1 = ctx.run_udf(udf=SumUDF(), dataset=ds)

In [11]:
sum_2 = ctx.run_udf(udf=SumUDF(), dataset=ds, roi=roi)

In [13]:
sum_1['intensity'].data - sum_2['intensity'].data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)